# Inference Runs on SAR Image Datasets
* Initially have 4k images from 10 Geophysical Phenomenon dataset paper that were classified as slick.
* Manually classified into E/NE classes.
* Run inference using fine-tuned weights we created from our own eddy datasets comprising around 30k images from Med and Cali. Fine-tuning done on pre-trained weights from SimCLR and MoCo trained on approx 100k random SAR eddy tiles. 

In [39]:
import os
import sys
from pathlib import Path
import datetime

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.metrics import confusion_matrix, accuracy_score, precision_score, recall_score

In [64]:
create_series = lambda fp : pd.read_csv(Path(fp), names=['res']).squeeze("columns")

In [65]:
# Results
res_simclr_val_med = create_series('datasets/preds_4k_slicks_ft_simclr_med_test_med_072377_01-03-24.out')
res_simclr_val_cal = create_series('datasets/preds_4k_slicks_ft_simrlr_med_test_cali_004244_01-03-24.out')
res_moco_val_med = create_series('datasets/preds_4k_slicks_ft_moco_med_test_med_185136_01-03-24.out')
res_moco_val_cal = create_series('datasets/preds_4k_slicks_ft_moco_med_test_cali_190008_01-03-24.out')

# Labels, Ben labeled 4k E/NE from slick (J) dataset
df_slicks = pd.read_csv('datasets/10gpp_slicks_labeled_ben.csv')

df_slicks.head()

img  label
0  GeoTIFF/J/s1a-wv2-slc-vv-20160612t162736-20160...      0
1  GeoTIFF/J/s1a-wv2-slc-vv-20160612t181008-20160...      0
2  GeoTIFF/J/s1a-wv2-slc-vv-20160612t185823-20160...      0
3  GeoTIFF/J/s1a-wv2-slc-vv-20160612t205509-20160...      0
4  GeoTIFF/J/s1a-wv2-slc-vv-20160613t064234-20160...      0

In [74]:
cf_simclr_val_med = confusion_matrix(df_slicks.label, res_simclr_val_med)
cf_simclr_val_cal = confusion_matrix(df_slicks.label, res_simclr_val_cal)
cf_moco_val_med = confusion_matrix(df_slicks.label, res_moco_val_med)
cf_moco_val_cal = confusion_matrix(df_slicks.label, res_moco_val_cal)

In [75]:
res_simclr_val_med

0       0
1       0
2       0
3       0
4       0
       ..
4701    0
4702    0
4703    1
4704    1
4705    1
Name: res, Length: 4706, dtype: int64

In [76]:
cf_simclr_val_med

array([[4012,  483],
       [ 154,   57]])

In [77]:
cf_simclr_val_cal

array([[4070,  425],
       [ 169,   42]])

In [78]:
cf_moco_val_med

array([[4233,  262],
       [ 188,   23]])

In [79]:
cf_moco_val_cal

array([[4357,  138],
       [ 182,   29]])